version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.0.0
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.3.0

defaults: &defaults
  working_directory: ~/repo


jobs:
  test:
    <<: *defaults

    docker:
      - image: cimg/node:18.15.0-browsers


    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-

      - run: yarn install

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules


workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/